### ISSUE TITLE
Can you share GNPs data 

### ISSUE THREAD

**Issue by rrcsw** [JosieHong/Mol_MassSpectra_MLP#1]
Can you share GNPs datasets or input data examples

**Comment by JosieHong** [comment]
Hi, 

Here is the link to GNPS: 
https://gnps.ucsd.edu/ProteoSAFe/libraries.jsp

Please cite their paper, when using it:
[Sharing and community curation of mass spectrometry data with Global Natural Products Social Molecular Networking](https://www.nature.com/articles/nbt.3597)

For the data preprocessing, our new paper is coming soon. I will not show it here. Thanks.
